name: Build
on:
  # Run on master and release branches
  push:
    branches: [main, "^v\\d+\\.\\d+$"]
  pull_request:
    branches: [main, "^v\\d+\\.\\d+$"]

jobs: 
  test:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.build_branch }}   
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: yarn
          cache-dependency-path: ./yarn.lock        
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build