name: Release

on:
  push:
    paths:
      - packages/types/**
      - packages/core-ui/**
  workflow_dispatch:
    inputs:
      release_core_ui:
        description: Release Core-UI
        required: true
        default: "minor"
        type: choice
        options:
        - major
        - minor
        - patch
      release_types:
        description: Release type
        required: true
        default: "minor"
        type: choice
        options:
        - major
        - minor
        - patch  
      target_branch:
        description: Branch to release
        required: true
        default: main
        type: string

permissions:
  actions: write
  contents: write

jobs:
  initialize:
    runs-on: ubuntu-20.04
    outputs:
      release_types: ${{ env.release_types }}
      release_core_ui: ${{ env.release_core_ui }}
      target_branch: ${{ env.target_branch }}
      types_package_change: ${{ steps.filter.outputs.types_package_change }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_branch || github.ref_name }}
        token: ${{ secrets.KIALI_PROJECT_TOKEN || github.token }}
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          types_package_change:
            - '.packages/types/**'
  publish_types:
    needs: [initialize]
    if: needs.initialize.outputs.types_package_change == 'true'   
    uses: ./.github/workflows/release-types.yml
    with:
      target_branch: ${{ github.event.inputs.target_branch || github.ref_name }}
      release_types: ${{ github.event.inputs.release_types || github.ref_name }}
  publish_core_ui:
    needs: [initialize, publish_types]    
    uses: ./.github/workflows/release-core-ui.yml
    with:
      target_branch: ${{ github.event.inputs.target_branch || github.ref_name }}
      release_core_ui: ${{ github.event.inputs.release_core_ui || github.ref_name }}
