name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        default: "minor"
        type: choice
        options:
        - major
        - minor
        - patch
      release_branch:
        description: Branch to release
        required: true
        default: main
        type: string

permissions:
  actions: write
  contents: write

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    outputs:
      release_type: ${{ env.release_type }}
      release_branch: ${{ env.release_version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.release_branch || github.ref_name }}
        token: ${{ secrets.KIALI_PROJECT_TOKEN || github.token }}
    - name: Configure git
      run: |
        git config user.email 'kialiProject@gmail.com'
        git config user.name 'kialiProject'
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: yarn
        cache-dependency-path: yarn.lock
    - name: Install dependencies and build 🔧
      run: yarn install && yarn run build    
    - name: Major release
      if: "${{ github.event.inputs.release_type == 'major' }}"
      run: yarn version --major --no-git-tag-version
    - name: Minor release
      if: "${{ github.event.inputs.release_type == 'minor' }}"
      run: yarn version --minor --no-git-tag-version
    - name: Patch release
      if: "${{ github.event.inputs.release_type == 'patch' }}"
      run: yarn version --patch --no-git-tag-version
    - name: Get version 
      run : |
        echo "NEW_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
    - name: Update changelog
      uses: superfaceai/release-changelog-action@v1
      with:
        path-to-changelog: CHANGELOG.md
        version: ${{ env.NEW_VERSION }}
        operation: release          
    - name: Publish package on Yarn 📦
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        yarn publish --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Push changes to repository
      run: |
        git add "package.json"
        git add "CHANGELOG.md"
        git commit -m "chore: release ${{ env.NEW_VERSION }}"
        git tag ${{ env.NEW_VERSION }}  
        git push origin && git push --tags
    # Read version changelog
    - id: get-changelog
      name: Get version changelog
      uses: superfaceai/release-changelog-action@v1
      with:
        path-to-changelog: CHANGELOG.md
        version: ${{ env.NEW_VERSION }}
        operation: read    
    # Update GitHub release with changelog
    - name: Update GitHub release documentation
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        body: ${{ steps.get-changelog.outputs.changelog }}
